server {
    listen 80;
    server_name 192.168.122.11;

    # ---- Front-end: build estático do React
    location / {
        root /var/www/armazem;
        index index.html;

        try_files $uri $uri/ /index.html;
    }

    # ---- API: encaminhamento para a VM2
    location /api/ {

        proxy_pass http://192.168.122.12:8080/;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10s;
        proxy_read_timeout    30s;
    }
}